@url=http://localhost:3000/users

### CRIAR
POST {{url}}
Content-Type: application/json

{
    "name": "josé",
    "email": "jose@gmail.com",
    "password": "543210",
    "birth": "2010-01-01"
}


### GET ALL
GET {{url}}

### Get by ID
GET {{url}}/6335ee8ce8a9c74c2085aca1